### ISSUE TITLE
方法似乎已经失效

### ISSUE THREAD

**Issue by Sciroccogti** [w2016561536/qndxx-jumpvideo#1]
代码中的路径已经不再匹配，并且我也没找到匹配的（

**Comment by w2016561536** [comment]
那您在python控制台界面有没有true或false的字符，如果有，那下次点击开始学习之前稍微等3s，如果没有，就需要重新确定内部存储的路径(理论上不把微信放在分身/多开里，就是我设置的目录。)

**Comment by w2016561536** [comment]
目前我这里测试是成功的，微信是最新版本。

**Comment by Sciroccogti** [comment]
我在进入main函数前添加了一行输出，然而在控制台中并没有输出这行字。
```Python
print('Starting...') # 有输出
while True:
    if os.path.exists(yourstorage+"Android/data/com.tencent.mm/files/VideoCache/tools") == True :
        print('Video detected!') # 未能输出
        main()
```

我翻阅了微信相关目录，我这里没有文件夹`VideoCache`。。

微信版本 7.0.18，MIUI 12，Android 9。

**Comment by w2016561536** [comment]
最近把这事给忘了，抱歉。

微信只有加载网页视频的时候，才会出现videocache,保存时间几小时左右，所以，qpython开在后台，会自动检测videocache是否存在。

**Comment by Sciroccogti** [comment]
目前仍未尝试成功。。如果有别人有相同错误的话再来开启本issue。

感谢您提供的方法！
