### ISSUE TITLE
微信缓存结构改变导致无法读取视频。

### ISSUE THREAD

**Issue by Preliterate** [w2016561536/qndxx-jumpvideo#2]
对着代码的路径找到了Android/data/com.tencent.mm/files/，但没有找到VideoCache文件夹。

或许是微信缓存结构更新所导致。

**Comment by w2016561536** [comment]
你这路径找的不对啊，要从根目录开始找

还有，只有加载视频网页时才会生成videocache

**Comment by w2016561536** [comment]
还有，你们有没有把微信放在分身里，放在分身里需要改路径

**Comment by Preliterate** [comment]
像小米的文件管理器打开的“内部存储设备”默认就是/storage/emulated/0/吗？

没有分身

**Comment by w2016561536** [comment]
如果是主用户，就是我默认设置的路径

**Comment by Sciroccogti** [comment]
确实是变了，我之前开过一个 issue #1

**Comment by Ari1311** [comment]
是不能用了吗？？？我试了没效果~~

**Comment by w2016561536** [comment]
刚刚看了一下，微信的视频缓存改成了隐藏文件，连接到电脑或者ES文件管理器就能看见

至于用不了的，在开始学习那个圆形按钮出现后等5秒试试，因为微信缓存可能有点多，一个一个遍历需要时间

**Comment by w2016561536** [comment]
@Ari1311  经过我多次测试，能正常使用。

**Comment by Preliterate** [comment]
终于摸到使用方法了。
在开始学习前等一段时间。
这段时间微信会将视频缓存到本地。
待缓存完成后之间点击开始即可。

**Comment by Preliterate** [comment]
完善了一下reamde。见PR
