### ISSUE TITLE
跳不过去，没反应

### ISSUE THREAD

**Issue by Mr-zhao98** [w2016561536/qndxx-jumpvideo#4]

**Comment by Mr-zhao98** [comment]
微信是主微信   分身关了   按路径也找到对应的文件夹了

**Comment by w2016561536** [comment]
是否在开始学习的界面等待？？建议时间大于5s。

**Comment by fjjking** [comment]
查看了微信的files目录发现发现在打开视频后没有VideoCache文件夹，可能是新一季的大学习加入了后台记录功能改版了？

**Comment by YINZHI-keji** [comment]
![](file:///home/wang/%E4%B8%8B%E8%BD%BD/Screenshot_20201107-210802_QPython%203L.jpg)
运行之后没有输出，也无法跳过食品。不运行程序在观看青年大学习时VideoCache文件夹内无文件

**Comment by YINZHI-keji** [comment]
![Screenshot_20201107-210802_QPython 3L](https://user-images.githubusercontent.com/36266781/98442097-a16e1580-213d-11eb-9366-fa20f5d0008e.jpg)

**Comment by w2016561536** [comment]
> 
> 
> ![](file:///home/wang/%E4%B8%8B%E8%BD%BD/Screenshot_20201107-210802_QPython%203L.jpg)
> 
> 运行之后没有输出，也无法跳过食品。不运行程序在观看青年大学习时VideoCache文件夹内无文件

这个问题我目前还没有遇到过，请问你是否给微信启用了分身等功能？因为安卓系统多用户是独立用户数据的

**Comment by YINZHI-keji** [comment]
开启了分身应用，但用的是主微信
微信版本7.0.19
尝试把Android/data/com.tencent.mm删除后让微信重建目录，依然没有出现VideoCache文件夹

**Comment by w2016561536** [comment]
> 开启了分身应用，但用的是主微信
> 
> 微信版本7.0.19
> 
> 尝试把Android/data/com.tencent.mm删除后让微信重建目录，依然没有出现VideoCache文件夹

我微信也是7.0.19

Videocache只会在浏览网页视频的时候出现，保持1天左右，并且路径在Android/data/com.tencent.mm/files里

能否在分身下看看有没有这个目录？

**Comment by YINZHI-keji** [comment]
分身下Android/data/com.tencent.mm是空的
可能是三星应用分身的问题
http://www.samsungmembers.cn/thread-977188-277-362.html

**Comment by w2016561536** [comment]
> 分身下Android/data/com.tencent.mm是空的
> 
> 可能是三星应用分身的问题
> 
> http://www.samsungmembers.cn/thread-977188-277-362.html

我的设备是三星A60,开了分身也没事啊。

**Comment by YINZHI-keji** [comment]
我是指DualApp/Android/data/com.tencent.mm/是空的、

**Comment by YINZHI-keji** [comment]
![Uploading Screenshot_20201107-223650_My Files.jpg…]()
重建之后的/Android/data/com.tencent.mm/files
并且 浏览了几次视频

**Comment by YINZHI-keji** [comment]
![Uploading Screenshot_20201107-223650_My Files.jpg…]()

**Comment by w2016561536** [comment]
你这图片载不出来啊
![Screenshot_20201107-225101_Samsung Internet](https://user-images.githubusercontent.com/40821031/98444355-34ae4780-214c-11eb-9edb-e69d1c6718d5.jpg)

**Comment by YINZHI-keji** [comment]
以经找到问题原因！

**Comment by YINZHI-keji** [comment]
系微信内置浏览器内核所致
 debugmm.qq.com/?forcex5=true
进入上述连接将浏览器内核切换为x5即可

**Comment by w2016561536** [comment]
@YINZHI-keji 能否分享一下?感谢！
